execute pathogen#infect()
"" Style / Powerline options
set laststatus=2 " Always display the statusline in all windows
set showtabline=2 " Always display the tabline, even if there is only one tab
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)

set background=dark
colorscheme jellybeans
syntax on

filetype plugin indent on
set autoindent
set nowrap

set incsearch 

set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

set showcmd
set number
set showmatch
